version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-bip
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: desafio_db
    ports:
      - "5432:5432"
    volumes:
      # Mantém os dados salvos no volume do Docker
      - postgres_data:/var/lib/postgresql/data
      # carregamento de scripts iniciais se tiver na pasta ./db
      - ./db:/docker-entrypoint-initdb.d

volumes:
  postgres_data: