-- db/schema.sql
CREATE TABLE IF NOT EXISTS BENEFICIO (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(255),
    VALOR DECIMAL(15,2) NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE,
    VERSION BIGINT DEFAULT 0 
);

CREATE TABLE IF NOT EXISTS HISTORICO_TRANSFERENCIA (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ORIGEM_ID BIGINT NOT NULL,
    DESTINO_ID BIGINT NOT NULL,
    VALOR DECIMAL(15,2) NOT NULL,
    DATA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ORIGEM_ID) REFERENCES BENEFICIO(ID),
    FOREIGN KEY (DESTINO_ID) REFERENCES BENEFICIO(ID)
);